export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_CONFIRMED = 'LOGIN_CONFIRMED';
