export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_CONFIRMED = 'LOGIN_CONFIRMED';
export const USERNAME_FIELD_UPDATED = 'USERNAME_FIELD_UPDATED';
export const PASSWORD_FIELD_UPDATED = 'PASSWORD_FIELD_UPDATED';
export const SWITCH_TO_REGISTER_MODE = 'SWITCH_TO_REGISTER_MODE';
export const SWITCH_TO_LOGIN_MODE = 'SWITCH_TO_LOGIN_MODE';
